version: '3.4'
services:
  app:
    build: .
    container_name: spacious-backend
    environment:
      - PORT=${PORT}
      - PORT_TEST=${PORT_TEST}
      - DB_URL=${DB_URL}
      - DB_URL_TEST=${DB_URL_TEST}
      - StrapiBearerToken=${StrapiBearerToken}
    ports:
      - "${PORT}:${PORT}"
      - "${PORT_TEST}:${PORT_TEST}"
    links:
      - db
    volumes:
      - .:/app/
    depends_on:
      - db
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB}, ${POSTGRES_DB_TEST}
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql'
    restart: always
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  pg_data:
